export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_ORDER = 'ADD_ORDER';
export const EMPTY_CART = 'EMPTY_CART';
export const UPDATE_ITEM_TO_CART = 'UPDATE_ITEM_TO_CART';
export const FETCH_CART_DATA = 'FETCH_CART_DATA';